### ISSUE TITLE
The `ghostkit_typography` query causing "MySQL server has gone away" error

### ISSUE THREAD

**Issue by bartoszgadomski** [nk-crew/ghostkit#205]
Context: we run the GhostKit plugin on a large WordPress multisite (network) installation, with approx. 200k+ posts and 1m+ post meta records.

While upgrading to v3 of this plugin we noticed multiple database errors in logs and significant drop in site performance.

```
PHP message: WordPress database error MySQL server has gone away for query SELECT * FROM `wp_postmeta` WHERE (`meta_key` LIKE '%ghostkit_typography%') LIMIT 50 made by GhostKit_Typography::typography_exist
```

We temporarily fixed that by using a custom hook to short-circuit the transient read operation:

```php
// Filter the "ghostkit_typography_exist" transient to avoid custom font loading and expensive DB query.
add_filter( 'pre_transient_ghostkit_typography_exist', function() { return 'false'; } );
```

The "LIKE" query operation with two wildcards (% character) is very expensive, especially that it runs against 1m+ records in our case.

Additionally, as we don't use the typography feature of this plugin, we also had to disable the `google_fonts_list` transient:

```php
// Reduce list of fonts the GhostKit plugin tries to load.
add_filter( 'pre_transient_ghostkit_google_fonts_list', '__return_empty_array' );
```

Ideally these logic should not run if a given feature of a plugin is not used. We solved that with a custom hooks but this is not a perfect solution (more like a "hack").

Our suggestion would be to:
- implement an admin toggle to turn off the plugin features that are not used
- provide a hook to programmatically opt-out from the plugin features that are not used
- execute logic associated with a given feature only when a given feature is enabled
- improve the query performance

Would it be possible to get that implemented in the GhostKit plugin?

**Comment by nk-o** [comment]
Thank you for info. There was a code, which was full of hacks. We wanted to integrate our Fonts feature with WordPress Fonts API https://make.wordpress.org/core/2021/09/28/implementing-a-webfonts-api-in-wordpress-core/.

Recently we decided to remove this hacky integration, since the Gutenberg team removed this API and rework it completely. https://github.com/nk-crew/ghostkit/commit/7384b6c0761fa9b9de02b03a39d60a93a0419c87
Currently preparing the new plugin update, which will not contain this issue.
